#!/usr/bin/env node
/**
 * 为 en.json 补充翻译
 * 策略：对 zh.json 中的每个 key，若 en.json 无对应值，
 * 用规则引擎做中英替换（常见中文词 → 英文），生成可用翻译。
 *
 * 用法：node scripts/fill-en.js
 */
const fs = require('fs');
const path = require('path');

const ZH_PATH = path.join(__dirname, '../src/renderer/js/lang/zh.json');
const EN_PATH = path.join(__dirname, '../src/renderer/js/lang/en.json');

const zh = JSON.parse(fs.readFileSync(ZH_PATH, 'utf8'));
const en = JSON.parse(fs.readFileSync(EN_PATH, 'utf8'));

// ── 规则映射表（中文短语 → 英文）───
const RULES = [
  ['🎵', ''], ['🔥', ''], ['📝', ''], ['📥', ''], ['🔄', ''], ['💡', ''], ['💾', ''],
  ['⚡', ''], ['⚠️', ''], ['✅', ''], ['❌', ''], ['♻️', ''], ['📍', ''],
  ['「」', '""'], ['“」', '""'], ['「', '"'], ['」', '"'],
  ['📦', ''], ['🔌', ''], ['🎨', ''], ['🌐', ''], ['📋', ''],
  ['—', '—'], ['。', '.'], ['，', ','], ['：', ':'], ['；', ';'],
  ['音乐下载器', 'MusicDL'],
  ['下载器', 'MusicDL'],
  ['网易云', 'Netease'], ['QQ音乐', 'QQ Music'], ['哔哩哔哩', 'Bilibili'], ['QQ音乐·', 'QQ Music·'],
  ['网易云·', 'Netease·'], ['哔哩哔哩', 'Bilibili'],
  ['首页', 'Home'], ['搜索', 'Search'], ['下载', 'Download'],
  ['本地歌曲', 'Local Songs'], ['下载历史', 'History'],
  ['AI 创作', 'AI Music'], ['格式转换', 'Converter'],
  ['设置', 'Settings'], ['Cookie', 'Cookie'],
  ['设置 / Cookie', 'Settings / Cookie'],
  ['全部平台', 'All'], ['全部', 'All'], ['网易', 'Netease'],
  ['格式：', 'Format:'], ['品质：', 'Quality:'], ['无损', 'FLAC'], ['标准', 'MP3'],
  ['操作', 'Actions'], ['导航', 'Nav'],
  ['下载目录', 'Download Path'], ['命名模板', 'Naming Template'],
  ['更改目录', 'Change'],
  ['变量', 'Vars'],
  ['发现好音乐，随时随地下载', 'Discover great music, anytime, anywhere'],
  ['支持网易云音乐、QQ音乐、哔哩哔哩三大平台，一键搜索下载，支持无损品质。',
   'Supports Netease, QQ Music and Bilibili. Search and download with one click, lossless quality.'],
  ['热门搜索', 'Trending'], ['点击搜索歌曲', 'Search songs...'],
  ['暂无歌曲，去', 'No songs yet, go to',],
  ['搜索音乐', 'Search music'],
  ['已加入下载队列', 'Added to download queue'],
  ['已加入队列', 'Added to queue'],
  ['加入队列', 'Add to queue'],
  ['已下载', 'Downloaded'], ['未下载', 'Pending'],
  ['已加入', 'Added'], ['已复制', 'Copied'],
  ['请先勾选要下载的歌曲', 'Select songs to download first'],
  ['没有可加入的歌曲（全部已下载）', 'All songs already downloaded'],
  ['批量加入失败', 'Batch add failed'],
  ['正在获取', 'Fetching'], ['获取', 'Fetch'],
  ['已获取下载链接', 'Download URL obtained'],
  ['暂无法获取下载链接', 'Download URL unavailable'],
  ['获取下载链接失败', 'Failed to get download URL'],
  ['命名模板已保存', 'Template saved'],
  ['初始化完成', 'Ready'], ['init 失败', 'Init failed'],
  ['恢复播放队列', 'Restored queue'],
  ['播放队列', 'Queue'], ['播放列表', 'Playlist'],
  ['最近播放已清空', 'History cleared'],
  ['播放统计已重置', 'Stats reset'],
  ['继续播放', 'Resume from'],
  ['从', 'Resume'],
  ['自动播放被拦截，请点击播放按钮', 'Autoplay blocked, click play'],
  ['使用嵌入歌词', 'Using embedded lyrics'],
  ['暂无法获取音源', 'Audio source unavailable'],
  ['音源获取失败', 'Audio source failed'],
  ['随机播放', 'Shuffle'],
  ['封面动画', 'Cover animation'],
  ['请输入有效的 API Key', 'Enter a valid API Key'],
  ['API Key 已保存', 'API Key saved'],
  ['请先配置 MiniMax API Key', 'Configure MiniMax API Key first'],
  ['请输入关键词/主题', 'Enter a topic'],
  ['已在线获取歌词（已保存为同名 .lrc）', 'Lyrics fetched and saved'],
  ['在线拉歌词失败：网络或接口异常', 'Failed to fetch lyrics: network error'],
  ['在线未找到该歌曲的歌词', 'No lyrics found online'],
  ['下载目录已更改', 'Download path changed'],
  ['扫描目录', 'Scan'],
  ['开始扫描本地歌曲', 'Scanning local songs...'],
  ['扫描完成', 'Scan complete'],
  ['已扫描', 'Scanned'],
  ['导入', 'Import'], ['导出', 'Export'],
  ['导入成功', 'Imported'], ['导出成功', 'Exported'],
  ['导出失败', 'Export failed'], ['导入失败', 'Import failed'],
  ['配置', 'Config'],
  ['云同步', 'Cloud Sync'],
  ['当前无播放歌曲', 'Nothing playing'],
  ['未知艺术家', 'Unknown'], ['未知专辑', 'Unknown Album'],
  ['正在搜索', 'Searching'],
  ['歌曲', 'songs'], ['首', ' songs'],
  ['播放', 'Play'], ['暂停', 'Pause'], ['停止', 'Stop'],
  ['上一首', 'Prev'], ['下一首', 'Next'],
  ['单曲循环', 'Repeat one'], ['列表循环', 'Repeat all'],
  ['顺序播放', 'Sequential'], ['随机播放 开', 'Shuffle: on'], ['随机播放 关', 'Shuffle: off'],
  ['播放模式', 'Mode'],
  ['歌词', 'Lyrics'], ['歌词偏移', 'Lyric offset'],
  ['设置', 'Settings'],
  ['关于 MusicDL', 'About MusicDL'],
  ['检查更新', 'Check updates'],
  ['当前已是最新版本', 'Already up to date'],
  ['发现新版本', 'New version available'],
  ['更新', 'Update'], ['更新中', 'Updating'],
  ['下载中', 'Downloading'], ['完成', 'Done'],
  ['打开下载目录', 'Open folder'],
  ['全部平台', 'All'],
  ['在线', 'Online'], ['本地', 'Local'],
  ['暂无数据', 'No data'],
  ['确认', 'OK'], ['取消', 'Cancel'],
  ['关闭', 'Close'], ['保存', 'Save'],
  ['是', 'Yes'], ['否', 'No'],
  ['中文', 'Chinese'], ['英文', 'English'],
  ['自动检测', 'Auto'],
  ['主题', 'Theme'], ['亮色', 'Light'], ['暗色', 'Dark'],
  ['跟随系统', 'System'],
  ['快捷键', 'Shortcuts'],
  ['快捷键已保存', 'Shortcuts saved'],
  ['歌词字体大小', 'Lyric font size'],
  ['字体大小', 'Font size'],
  ['歌词行距', 'Line height'],
  ['歌词显示', 'Lyric display'],
  ['翻译', 'Translation'],
  ['显示罗马音', 'Romaji'],
  ['已保存', 'Saved'], ['已清空', 'Cleared'],
  ['已重置', 'Reset'],
  ['成功', 'Success'], ['失败', 'Failed'],
  ['请', 'Please'], ['请检查', 'Check'],
  ['错误', 'Error'], ['警告', 'Warning'],
  ['提示', 'Tip'],
  ['暂无', 'None'],
  ['全部', 'All'],
  ['全部歌曲', 'All songs'],
  ['全部文件夹', 'All folders'],
  ['按名称', 'By name'], ['按时间', 'By time'],
  ['排序', 'Sort'], ['筛选', 'Filter'],
  ['搜索框', 'Search'], ['结果', 'Results'],
  ['共', 'Total'],
  ['加载中', 'Loading'], ['加载失败', 'Load failed'],
  ['网络错误', 'Network error'],
  ['重试', 'Retry'], ['稍后再试', 'Try again'],
  ['已登录', 'Logged in'], ['未登录', 'Not logged in'],
  ['登录', 'Login'], ['退出', 'Logout'],
  ['账户', 'Account'], ['密码', 'Password'],
  ['邮箱', 'Email'], ['手机号', 'Phone'],
  ['验证码', 'Code'], ['发送验证码', 'Send code'],
  ['发送成功', 'Sent'],
  ['绑定', 'Link'], ['解绑', 'Unlink'],
  ['已启用', 'Enabled'], ['已禁用', 'Disabled'],
  ['启用', 'Enable'], ['禁用', 'Disable'],
  ['开', 'On'], ['关', 'Off'],
  ['是/否', 'Yes/No'],
  ['正在', 'Now'], ['已完成', 'Completed'],
  ['已取消', 'Cancelled'],
  ['正在进行', 'In progress'],
  ['暂停中', 'Paused'],
  ['取消中', 'Cancelling'],
  ['下载中', 'Downloading'],
  ['已暂停', 'Paused'],
  ['正在转换', 'Converting'],
  ['转换完成', 'Converted'],
  ['转换失败', 'Convert failed'],
  ['创建文件夹', 'Create folder'],
  ['文件夹名', 'Folder name'],
  ['已创建', 'Created'],
  ['已删除', 'Deleted'],
  ['确认删除', 'Confirm delete'],
  ['正在删除', 'Deleting'],
  ['删除失败', 'Delete failed'],
  ['已移动', 'Moved'],
  ['正在移动', 'Moving'],
  ['移动失败', 'Move failed'],
  ['已重命名', 'Renamed'],
  ['正在重命名', 'Renaming'],
  ['重命名失败', 'Rename failed'],
  ['已复制', 'Copied'],
  ['复制失败', 'Copy failed'],
  ['已粘贴', 'Pasted'],
  ['粘贴失败', 'Paste failed'],
  ['已剪切', 'Cut'],
  ['剪切失败', 'Cut failed'],
  ['全部选中', 'Select all'],
  ['取消选择', 'Deselect'],
  ['选中', 'Selected'],
  ['未选中', 'Unselected'],
  ['全部播放', 'Play all'],
  ['暂停全部', 'Pause all'],
  ['停止全部', 'Stop all'],
  ['清空列表', 'Clear list'],
  ['清空', 'Clear'],
  ['添加', 'Add'],
  ['移除', 'Remove'],
  ['编辑', 'Edit'],
  ['查看详情', 'Details'],
  ['打开', 'Open'],
  ['关闭', 'Close'],
  ['最小化', 'Minimize'],
  ['最大化', 'Maximize'],
  ['恢复', 'Restore'],
  ['置顶', 'Pin'],
  ['取消置顶', 'Unpin'],
  ['全屏', 'Fullscreen'],
  ['退出全屏', 'Exit fullscreen'],
  ['截图', 'Screenshot'],
  ['刷新', 'Refresh'],
  ['撤销', 'Undo'],
  ['重做', 'Redo'],
  ['前进', 'Forward'],
  ['后退', 'Back'],
  ['主页', 'Home'],
  ['书签', 'Bookmark'],
  ['收藏', 'Favorite'],
  ['已收藏', 'Favorited'],
  ['取消收藏', 'Unfavorite'],
  ['分享', 'Share'],
  ['复制链接', 'Copy link'],
  ['复制链接成功', 'Link copied'],
  ['打印', 'Print'],
  ['导出', 'Export'],
  ['导入', 'Import'],
  ['导入成功', 'Imported'],
  ['导出成功', 'Exported'],
  ['另存为', 'Save as'],
  ['打开方式', 'Open with'],
  ['属性', 'Properties'],
  ['新建', 'New'],
  ['新建文件', 'New file'],
  ['新建文件夹', 'New folder'],
  ['保存为', 'Save as'],
  ['另存', 'Save as'],
  ['覆盖', 'Overwrite'],
  ['跳过', 'Skip'],
  ['替换', 'Replace'],
  ['取消', 'Cancel'],
  ['确定', 'OK'],
  ['应用', 'Apply'],
  ['重置', 'Reset'],
  ['默认', 'Default'],
  ['高级', 'Advanced'],
  ['基础', 'Basic'],
  ['选项', 'Options'],
  ['偏好', 'Preferences'],
  ['自定义', 'Custom'],
  ['预设', 'Preset'],
  ['模板', 'Template'],
  ['样式', 'Style'],
  ['布局', 'Layout'],
  ['显示', 'Display'],
  ['隐藏', 'Hide'],
  ['可见', 'Visible'],
  ['不可见', 'Invisible'],
  ['透明', 'Transparent'],
  ['不透明', 'Opaque'],
  ['居中', 'Center'],
  ['对齐', 'Align'],
  ['左对齐', 'Left'],
  ['右对齐', 'Right'],
  ['上对齐', 'Top'],
  ['下对齐', 'Bottom'],
  ['自适应', 'Auto-fit'],
  ['缩放', 'Zoom'],
  ['放大', 'Zoom in'],
  ['缩小', 'Zoom out'],
  ['恢复默认', 'Reset to default'],
  ['锁定', 'Lock'],
  ['解锁', 'Unlock'],
  ['隐藏任务栏', 'Hide from taskbar'],
  ['启动时自动运行', 'Start with system'],
  ['启动', 'Launch'],
  ['自动启动', 'Auto-start'],
  ['开机启动', 'Start on boot'],
  ['开机', 'Boot'],
  ['启动项', 'Startup'],
  ['后台', 'Background'],
  ['前台', 'Foreground'],
  ['置顶窗口', 'Always on top'],
  ['最小化到托盘', 'Minimize to tray'],
  ['托盘', 'Tray'],
  ['通知', 'Notification'],
  ['通知区域', 'Notification area'],
  ['系统通知', 'System notification'],
  ['桌面通知', 'Desktop notification'],
  ['弹窗', 'Popup'],
  ['气泡', 'Balloon'],
  ['横幅', 'Banner'],
  ['卡片', 'Card'],
  ['标签', 'Tab'],
  ['页签', 'Tab'],
  ['标签页', 'Tab'],
  ['窗口', 'Window'],
  ['标签栏', 'Tab bar'],
  ['菜单栏', 'Menu bar'],
  ['工具栏', 'Toolbar'],
  ['状态栏', 'Status bar'],
  ['地址栏', 'Address bar'],
  ['搜索栏', 'Search bar'],
  ['导航栏', 'Navigation bar'],
  ['侧边栏', 'Sidebar'],
  ['内容区', 'Content'],
  ['标题栏', 'Title bar'],
  ['滚动条', 'Scrollbar'],
  ['分隔符', 'Divider'],
  ['边框', 'Border'],
  ['背景', 'Background'],
  ['前景', 'Foreground'],
  ['文本', 'Text'],
  ['字体', 'Font'],
  ['字号', 'Font size'],
  ['字重', 'Font weight'],
  ['字间距', 'Letter spacing'],
  ['行高', 'Line height'],
  ['段落', 'Paragraph'],
  ['缩进', 'Indent'],
  ['列表', 'List'],
  ['有序列表', 'Ordered list'],
  ['无序列表', 'Unordered list'],
  ['表格', 'Table'],
  ['单元格', 'Cell'],
  ['行', 'Row'],
  ['列', 'Column'],
  ['表头', 'Header'],
  ['表体', 'Body'],
  ['表脚', 'Footer'],
  ['合并单元格', 'Merge cells'],
  ['拆分红利', 'Split'],
  ['添加行', 'Add row'],
  ['添加列', 'Add column'],
  ['删除行', 'Delete row'],
  ['删除列', 'Delete column'],
  ['排序行', 'Sort rows'],
  ['排序列', 'Sort columns'],
  ['筛选行', 'Filter rows'],
  ['筛选列', 'Filter columns'],
  ['查找', 'Find'],
  ['查找并替换', 'Find and replace'],
  ['替换', 'Replace'],
  ['全部替换', 'Replace all'],
  ['匹配大小写', 'Match case'],
  ['整词匹配', 'Whole word'],
  ['正则表达式', 'Regex'],
  ['向上查找', 'Search up'],
  ['向下查找', 'Search down'],
  ['查找上一个', 'Find previous'],
  ['查找下一个', 'Find next'],
  ['跳到', 'Go to'],
  ['跳到行', 'Go to line'],
  ['跳到列', 'Go to column'],
  ['跳到单元格', 'Go to cell'],
  ['选择', 'Select'],
  ['全选', 'Select all'],
  ['反选', 'Invert selection'],
  ['选择行', 'Select row'],
  ['选择列', 'Select column'],
  ['选择单元格', 'Select cell'],
  ['选择区域', 'Select range'],
  ['取消选择', 'Deselect'],
  ['清除选择', 'Clear selection'],
];

// ── 应用规则 ──────────────────────────────
function translateZhToEn(text) {
  let result = text;
  for (const [zh, enText] of RULES) {
    result = result.split(zh).join(enText);
  }
  return result;
}

// ── 主逻辑 ────────────────────────────────
let added = 0;
const keys = Object.keys(zh);

for (const key of keys) {
  if (en[key] === undefined) {
    en[key] = translateZhToEn(zh[key]);
    added++;
  }
}

fs.writeFileSync(EN_PATH, JSON.stringify(en, null, 2) + '\n');
console.log(`Added ${added} missing translations to en.json`);
console.log(`en.json now: ${Object.keys(en).length} entries (was ${Object.keys(en).length - added})`);